---
version: "3.7"


services:
  nifi:
    image: apache/nifi:1.19.1
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
      - "8181:8181"
      - "8443:8443"
      - "10000:10000"
    volumes:
      - type: volume
        source: conf
        target: /opt/nifi/current/conf
      - type: volume
        source: content
        target: /opt/nifi/current/content_repository
      - type: volume
        source: db
        target: /opt/nifi/current/database_repository
      - type: volume
        source: flowfile
        target: /opt/nifi/current/flowfile_repository
      - type: volume
        source: provenance
        target: /opt/nifi/current/provenance_repository
      - type: volume
        source: logs
        target: /opt/nifi/current/logs
      - type: volume
        source: data
        target: /opt/nifi/current/data
volumes:
  conf:
  content:
  db:
  flowfile:
  provenance:
  logs:
  data:
...
