---
version: "3.7"


services:
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi:1.19.1
    deploy:
      replicas: 1
    environment:
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_WEB_HTTP_PORT: 8080  
      SINGLE_USER_CREDENTIALS_USERNAME: admin      
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      NIFI_WEB_PROXY_HOST: srxlt8-8080.csb.app:8080
    expose:
      - "8443"      
      - "8080"
      - "8181"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host 
      - "8181:8181"
      - "8443:8443"
      - "10000:10000"
    volumes:
      - type: volume
        source: conf
        target: /opt/nifi/current/conf
      - type: volume
        source: content
        target: /opt/nifi/current/content_repository
      - type: volume
        source: db
        target: /opt/nifi/current/database_repository
      - type: volume
        source: flowfile
        target: /opt/nifi/current/flowfile_repository
      - type: volume
        source: provenance
        target: /opt/nifi/current/provenance_repository
      - type: volume
        source: logs
        target: /opt/nifi/current/logs
      - type: volume
        source: data
        target: /opt/nifi/current/data
volumes:
  conf:
  content:
  db:
  flowfile:
  provenance:
  logs:
  data:
...
